import { CellType, IBoard } from '@common/board';
import { ItemType } from '@common/items';

/* eslint-disable max-lines */
// Separate constant file since it would make board.service.spec hard to read to have
// them all in the test file

export const validClassicBoard: IBoard = {
    cells: [
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Wall,
            CellType.OpenDoor,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
    ],
    items: [
        {
            itemType: ItemType.StartingPosition,
            x: 0,
            y: 0,
            size: 1,
        },
        {
            itemType: ItemType.StartingPosition,
            x: 3,
            y: 3,
            size: 1,
        },
        {
            itemType: ItemType.FightSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
        {
            itemType: ItemType.LifeSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
    ],
};

const verticalDoorTopWallOnlyCells = validClassicBoard.cells.map((row) => [...row]);
verticalDoorTopWallOnlyCells[0][1] = CellType.Wall;
verticalDoorTopWallOnlyCells[1][1] = CellType.OpenDoor;

export const verticalDoorTopWallOnlyBoard: IBoard = {
    cells: verticalDoorTopWallOnlyCells,
    items: validClassicBoard.items.map((item) => ({ ...item })),
};

const verticalDoorWithWallsCells = validClassicBoard.cells.map((row) => [...row]);
verticalDoorWithWallsCells[1][1] = CellType.OpenDoor;
verticalDoorWithWallsCells[0][1] = CellType.Wall;
verticalDoorWithWallsCells[2][1] = CellType.Wall;

export const verticalDoorWithWallsBoard: IBoard = {
    cells: verticalDoorWithWallsCells,
    items: validClassicBoard.items.map((item) => ({ ...item })),
};

export const invalidSizeBoard: IBoard = {
    cells: [
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
    ],
    items: [
        {
            itemType: ItemType.StartingPosition,
            x: 0,
            y: 0,
            size: 1,
        },
        {
            itemType: ItemType.StartingPosition,
            x: 3,
            y: 3,
            size: 1,
        },
        {
            itemType: ItemType.FightSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
        {
            itemType: ItemType.LifeSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
    ],
};

export const insufficientStartingPointsSmallBoard: IBoard = {
    cells: [
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
    ],
    items: [
        {
            itemType: ItemType.StartingPosition,
            x: 3,
            y: 3,
            size: 1,
        },
        {
            itemType: ItemType.FightSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
        {
            itemType: ItemType.LifeSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
    ],
};

export const ctfNoFlagMediumBoard: IBoard = {
    cells: [
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
    ],
    items: [
        { itemType: ItemType.StartingPosition, x: 3, y: 3, size: 1 },
        { itemType: ItemType.StartingPosition, x: 11, y: 11, size: 1 },
        { itemType: ItemType.FightSanctuary, x: 5, y: 5, size: 4 },
        { itemType: ItemType.LifeSanctuary, x: 9, y: 9, size: 4 },
    ],
};

export const insufficientStartingPointsLargeBoard: IBoard = {
    cells: [
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
        ],
    ],
    items: [
        { itemType: ItemType.StartingPosition, x: 0, y: 0, size: 1 },
        { itemType: ItemType.FightSanctuary, x: 5, y: 5, size: 4 },
        { itemType: ItemType.FightSanctuary, x: 5, y: 5, size: 4 },
        { itemType: ItemType.FightSanctuary, x: 5, y: 5, size: 4 },
        { itemType: ItemType.LifeSanctuary, x: 10, y: 10, size: 4 },
        { itemType: ItemType.LifeSanctuary, x: 10, y: 10, size: 4 },
        { itemType: ItemType.LifeSanctuary, x: 10, y: 10, size: 4 },
        { itemType: ItemType.FightSanctuary, x: 15, y: 15, size: 4 },
        { itemType: ItemType.LifeSanctuary, x: 19, y: 19, size: 4 },
    ],
};

export const unreachableBoard: IBoard = {
    cells: [
        [
            CellType.Ice,
            CellType.Wall,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Wall,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
    ],
    items: [
        {
            itemType: ItemType.StartingPosition,
            x: 3,
            y: 3,
            size: 1,
        },
        {
            itemType: ItemType.StartingPosition,
            x: 3,
            y: 3,
            size: 1,
        },
        {
            itemType: ItemType.FightSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
        {
            itemType: ItemType.LifeSanctuary,
            x: 5,
            y: 5,
            size: 4,
        },
    ],
};

export const halfTerrainBoard: IBoard = {
    cells: [
        [
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Ice,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Ice,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Ice,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Ice,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Ice,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Ice,
            CellType.Grass,
            CellType.Grass,
        ],
        [
            CellType.Grass,
            CellType.Grass,
            CellType.Ice,
            CellType.Grass,
            CellType.Grass,
            CellType.Grass,
            CellType.Ice,
            CellType.Grass,
            CellType.Grass,
            CellType.Grass,
        ],
        [
            CellType.Grass,
            CellType.Ice,
            CellType.Grass,
            CellType.Grass,
            CellType.Grass,
            CellType.Ice,
            CellType.Grass,
            CellType.Grass,
            CellType.Grass,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Grass,
            CellType.Grass,
            CellType.Grass,
            CellType.Ice,
            CellType.Grass,
            CellType.Grass,
            CellType.Grass,
            CellType.Ice,
            CellType.Grass,
        ],
        [
            CellType.Grass,
            CellType.Grass,
            CellType.Ice,
            CellType.Grass,
            CellType.Grass,
            CellType.Grass,
            CellType.Ice,
            CellType.Grass,
            CellType.Grass,
            CellType.Grass,
        ],
    ],
    items: [
        {
            itemType: ItemType.StartingPosition,
            x: 3,
            y: 3,
            size: 1,
        },
        {
            itemType: ItemType.StartingPosition,
            x: 3,
            y: 3,
            size: 1,
        },
        {
            itemType: ItemType.FightSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
        {
            itemType: ItemType.LifeSanctuary,
            x: 5,
            y: 5,
            size: 4,
        },
    ],
};

export const allWallsBoard: IBoard = {
    cells: [
        [
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
            CellType.Wall,
        ],
    ],
    items: [
        {
            itemType: ItemType.StartingPosition,
            x: 3,
            y: 3,
            size: 1,
        },
        {
            itemType: ItemType.StartingPosition,
            x: 3,
            y: 3,
            size: 1,
        },
        {
            itemType: ItemType.FightSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
        {
            itemType: ItemType.LifeSanctuary,
            x: 5,
            y: 5,
            size: 4,
        },
    ],
};

export const ctfNoFlagSmallBoard: IBoard = {
    cells: [
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
    ],
    items: [
        {
            itemType: ItemType.StartingPosition,
            x: 0,
            y: 0,
            size: 1,
        },
        {
            itemType: ItemType.StartingPosition,
            x: 3,
            y: 3,
            size: 1,
        },
        {
            itemType: ItemType.FightSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
        {
            itemType: ItemType.LifeSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
    ],
};

export const invalidDoorBoard: IBoard = {
    cells: [
        [
            CellType.Ice,
            CellType.Water,
            CellType.OpenDoor,
            CellType.Wall,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
    ],
    items: [
        {
            itemType: ItemType.StartingPosition,
            x: 0,
            y: 0,
            size: 1,
        },
        {
            itemType: ItemType.StartingPosition,
            x: 3,
            y: 3,
            size: 1,
        },
        {
            itemType: ItemType.FightSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
        {
            itemType: ItemType.LifeSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
    ],
};

export const edgeDoorBoard: IBoard = {
    cells: [
        [
            CellType.OpenDoor,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Wall,
            CellType.OpenDoor,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
    ],
    items: [
        {
            itemType: ItemType.StartingPosition,
            x: 0,
            y: 0,
            size: 1,
        },
        {
            itemType: ItemType.StartingPosition,
            x: 3,
            y: 3,
            size: 1,
        },
        {
            itemType: ItemType.FightSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
        {
            itemType: ItemType.LifeSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
    ],
};

export const topEdgeDoorBoard: IBoard = {
    cells: [
        [
            CellType.Wall,
            CellType.OpenDoor,
            CellType.Wall,
            CellType.Ice,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Wall,
            CellType.OpenDoor,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
        ],
        [
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Water,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
        ],
        [
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
            CellType.Water,
            CellType.Ice,
            CellType.Water,
            CellType.Wall,
        ],
    ],
    items: [
        {
            itemType: ItemType.StartingPosition,
            x: 0,
            y: 0,
            size: 1,
        },
        {
            itemType: ItemType.StartingPosition,
            x: 3,
            y: 3,
            size: 1,
        },
        {
            itemType: ItemType.FightSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
        {
            itemType: ItemType.LifeSanctuary,
            x: 1,
            y: 1,
            size: 4,
        },
    ],
};
