/* eslint-disable max-lines -- Test file requires many test cases with extensive board configurations to cover all validation branches */
import { CellType, IBoard } from '@common/board';
import { GameType } from '@common/game';
import { expect } from 'chai';
import { Container } from 'typedi';
import { BoardService } from './board.service';

describe('Board Service', () => {
    let boardService: BoardService;

    beforeEach(async () => {
        boardService = Container.get(BoardService);
    });

    it('should return true when validating a valid board', () => {
        const board: IBoard = {
            cells: [
                [
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Water,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Water,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Water,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                ],
            ],
            items: [
                {
                    itemType: 'startingPosition',
                    x: 0,
                    y: 0,
                    size: 1,
                },
                {
                    itemType: 'startingPosition',
                    x: 3,
                    y: 3,
                    size: 1,
                },
                {
                    itemType: 'fightSanctuary',
                    x: 1,
                    y: 1,
                    size: 4,
                },
                {
                    itemType: 'lifeSanctuary',
                    x: 1,
                    y: 1,
                    size: 4,
                },
            ],
        };

        const errors = boardService.validateBoard(board, GameType.Classic);
        expect(errors).to.have.lengthOf(0);
    });

    it('should return false for invalid board size', () => {
        const board: IBoard = {
            cells: [
                [
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Water,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Water,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Water,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                ],
                [
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                ],
            ],
            items: [
                {
                    itemType: 'startingPosition',
                    x: 0,
                    y: 0,
                    size: 1,
                },
                {
                    itemType: 'startingPosition',
                    x: 3,
                    y: 3,
                    size: 1,
                },
                {
                    itemType: 'fightSanctuary',
                    x: 1,
                    y: 1,
                    size: 4,
                },
                {
                    itemType: 'lifeSanctuary',
                    x: 1,
                    y: 1,
                    size: 4,
                },
            ],
        };

        const errors = boardService.validateBoard(board, GameType.Classic);
        expect(errors).to.include('La taille de la carte est invalide.');
    });

    it('should return false when board doesnt have enough starting points for small board', () => {
        const board: IBoard = {
            cells: [
                [
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Water,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Water,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Water,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                ],
            ],
            items: [
                {
                    itemType: 'startingPosition',
                    x: 3,
                    y: 3,
                    size: 1,
                },
                {
                    itemType: 'fightSanctuary',
                    x: 1,
                    y: 1,
                    size: 4,
                },
                {
                    itemType: 'lifeSanctuary',
                    x: 1,
                    y: 1,
                    size: 4,
                },
            ],
        };

        const errors = boardService.validateBoard(board, GameType.Classic);
        expect(errors).to.include('Le nombre de positions de départ est invalide.');
    });

    it('should return false when board doesnt have enough starting points for large board', () => {
        const board: IBoard = {
            cells: [
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                    CellType.Ice,
                ],
            ],
            items: [
                { itemType: 'startingPosition', x: 0, y: 0, size: 1 },
                { itemType: 'fightSanctuary', x: 5, y: 5, size: 4 },
                { itemType: 'lifeSanctuary', x: 10, y: 10, size: 4 },
                { itemType: 'fightSanctuary', x: 15, y: 15, size: 4 },
                { itemType: 'lifeSanctuary', x: 19, y: 19, size: 4 },
            ],
        };

        const errors = boardService.validateBoard(board, GameType.Classic);
        expect(errors).to.include('Le nombre de positions de départ est invalide.');
    });

    it('should return false when board has unreachable ', () => {
        const board: IBoard = {
            cells: [
                [
                    CellType.Ice,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                ],
                [
                    CellType.Wall,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Water,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Water,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Water,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                ],
                [
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                    CellType.Water,
                    CellType.Ice,
                    CellType.Water,
                    CellType.Wall,
                ],
            ],
            items: [
                {
                    itemType: 'startingPosition',
                    x: 3,
                    y: 3,
                    size: 1,
                },
                {
                    itemType: 'startingPosition',
                    x: 3,
                    y: 3,
                    size: 1,
                },
                {
                    itemType: 'fightSanctuary',
                    x: 1,
                    y: 1,
                    size: 4,
                },
                {
                    itemType: 'lifeSanctuary',
                    x: 5,
                    y: 5,
                    size: 4,
                },
            ],
        };

        const errors = boardService.validateBoard(board, GameType.Classic);
        expect(errors).to.include('Toutes les cellules de la carte ne sont pas accessibles.');
    });

    it('should return false when 50% or more of the board is empty', () => {
        const board: IBoard = {
            cells: [
                [
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                ],
                [
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                ],
                [
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Wall,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                ],
                [
                    CellType.Empty,
                    CellType.Ice,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Ice,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Ice,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Ice,
                    CellType.Empty,
                ],
                [
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Ice,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Ice,
                    CellType.Empty,
                    CellType.Empty,
                ],
                [
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Ice,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Ice,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                ],
                [
                    CellType.Empty,
                    CellType.Ice,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Ice,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Ice,
                ],
                [
                    CellType.Ice,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Ice,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Ice,
                    CellType.Empty,
                ],
                [
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Ice,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Ice,
                    CellType.Empty,
                    CellType.Empty,
                    CellType.Empty,
                ],
            ],
            items: [
                {
                    itemType: 'startingPosition',
                    x: 3,
                    y: 3,
                    size: 1,
                },
                {
                    itemType: 'startingPosition',
                    x: 3,
                    y: 3,
                    size: 1,
                },
                {
                    itemType: 'fightSanctuary',
                    x: 1,
                    y: 1,
                    size: 4,
                },
                {
                    itemType: 'lifeSanctuary',
                    x: 5,
                    y: 5,
                    size: 4,
                },
            ],
        };

        const errors = boardService.validateBoard(board, GameType.Classic);
        expect(errors).to.include('Moins de 50% de la surface totale de la carte est couverte par des tuiles.');
    });

    it('should return false when the board is all walls', () => {
        const board: IBoard = {
            cells: [
                [
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                ],
                [
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                    CellType.Wall,
                ],
            ],
            items: [
                {
                    itemType: 'startingPosition',
                    x: 3,
                    y: 3,
                    size: 1,
                },
                {
                    itemType: 'startingPosition',
                    x: 3,
                    y: 3,
                    size: 1,
                },
                {
                    itemType: 'fightSanctuary',
                    x: 1,
                    y: 1,
                    size: 4,
                },
                {
                    itemType: 'lifeSanctuary',
                    x: 5,
                    y: 5,
                    size: 4,
                },
            ],
        };
        const errors = boardService.validateBoard(board, GameType.Classic);
        expect(errors).to.include('Toutes les cellules de la carte ne sont pas accessibles.');
    });
});
