import { MILLISECONDS_PER_SECOND, SECONDS_PER_MINUTE } from '@common/constants';

const ONE_MINUTE_MS = SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND;

export const ACTIVE_GAME_SWEEP_INTERVAL_MS = ONE_MINUTE_MS;
export const ACTIVE_GAME_SWEEP_GRACE_PERIOD_MS = 2 * ONE_MINUTE_MS;
