export const SANCTUARY_ACTION_COST = 1;
export const LIFE_SANCTUARY_STANDARD_HEAL_AMOUNT = 2;
export const LIFE_SANCTUARY_DOUBLE_HEAL_AMOUNT = 4;
export const FIGHT_SANCTUARY_STANDARD_BONUS = 1;
export const FIGHT_SANCTUARY_DOUBLE_BONUS = 2;
export const FIGHT_SANCTUARY_BUFF_TURNS = 2;
export const SANCTUARY_DOUBLE_CHANCE = 0.5;
