export const CHAT_PANEL_AUTO_SCROLL_BOUNDARY_PX = 80;
export const CHAT_PANEL_MAX_MESSAGE_LENGTH = 200;
export const CHAT_PANEL_MIN_MESSAGE_LENGTH = 1;
export const CHAT_PANEL_INVALID_SUBMISSION_FEEDBACK_DURATION_MS = 2000;
export const WAIT_ROOM_MIN_PLAYERS_TO_START = 2;
