export const TOOLTIP_VERTICAL_OFFSET_PX = 8;
export const TOOLTIP_HORIZONTAL_OFFSET_PX = 12;
export const TOOLTIP_FALLBACK_HEIGHT_PX = 80;
export const GAME_TABLE_TOOLTIP_FALLBACK_WIDTH_PX = 200;
export const GAME_GRID_PANEL_TOOLTIP_FALLBACK_WIDTH_PX = 240;
export const TOOLTIP_CONTROLLER_VERTICAL_OFFSET_PX = 24;
export const TOOLTIP_CONTROLLER_FALLBACK_WIDTH_PX = 200;
export const TOOLTIP_CONTROLLER_FALLBACK_HEIGHT_PX = 80;
